#!/bin/bash
check_for="Infor Workforce Management"
MAILTO="safir.salihu@wnco.com,dan.gilbert@wnco.com"
NOTIFICATION_COUNT=3
env=""

while [ $# -ge 1 ]
do
key="$1"

case $key in
    -d1|--dev1)
	env="dev1"
    STOP_FILE="/tmp/stop-infor-check-${env}.txt"
    LOCK_FILE="/tmp/infor-check-${env}.lck"
    shift # past argument
    ;;
    -d2|--dev2)
	env="dev2"
    STOP_FILE="/tmp/stop-infor-check-${env}.txt"
    LOCK_FILE="/tmp/infor-check-${env}.lck"
    shift # past argument
    ;;
    -d3|--dev3)
	env="dev3"
    STOP_FILE="/tmp/stop-infor-check-${env}.txt"
    LOCK_FILE="/tmp/infor-check-${env}.lck"
    shift # past argument
    ;;
    -i1|--itest1)
	env="itest1"
    STOP_FILE="/tmp/stop-infor-check-${env}.txt"
    LOCK_FILE="/tmp/infor-check-${env}.lck"
    nodes[0]="http://xlteip26.swacorp.com:9080/infor/"
    nodes[1]="http://xlteip27.swacorp.com:9081/infor/"
    shift # past argument
    ;;
    -i2|--itest2)
	env="itest2
    STOP_FILE="/tmp/stop-infor-check-itest2.txt"
    LOCK_FILE="/tmp/infor-check-itest2.lck"
    nodes[0]="http://xlteip26.swacorp.com:9081/infor/LLLL"
    nodes[1]="http://xlteip27.swacorp.com:9082/infor/"
     shift # past argument
    ;;
    --default)
    DEFAULT=YES
    ;;
    *)
            # unknown option
    ;;
esac
shift # past argument or value
done
CONTENT="./res-${env}.html"
STOP_FILE="/tmp/stop-infor-check-${env}.txt"
LOCK_FILE="/tmp/infor-check-${env}.lck"

if [ -f $STOP_FILE ];
then
   exit
fi

if [ -f $CONTENT ];
then
   rm $CONTENT
# fi

error_state=""
logs=()
for node in ${nodes[*]}
do
    url1="$(curl -s "$node" |grep "$check_for")"
    if [ x"$url1" == x"" ];
    then
       error_state=$node
       len=${#logs[*]} 
       logs[len]="$error_state <br>" 
    fi
    printf "   %s\n" $item
done

SUBJECT="ERROR Accessing Workbrain in ${env}"


# len=${#logs[*]} 

counter=0
if [ $len -gt 0 ];
then
   echo "<html><body>" >> $CONTENT
   echo "<p> <font color="red"> The below URL(s) are not accessible </font></p>" >> $CONTENT

   if [ -f $LOCK_FILE ];
   then
      counter=`cat $LOCK_FILE`
      echo "$(($counter+1))" > $LOCK_FILE
   else
      counter=1
      echo $counter > $LOCK_FILE
   fi
else
   if [ -f $LOCK_FILE ];
   then
      counter=`cat $LOCK_FILE`
   fi

   if [ $counter -ne 0 ];
   then
         SUBJECT="Workbrain has recovered in ${env}"
         echo "<html><body>" >> $CONTENT
         echo "<p> <font color="green"> INFOR app has recovered in ${env} </font></p>" >> $CONTENT
         echo "</html></body>" >> $CONTENT
   fi
    counter=0
    echo $counter > $LOCK_FILE   
fi

counter=`cat $LOCK_FILE`

for i in "${logs[@]}"
do
   : 
   echo $i >> $CONTENT
done

if [ $len -gt 0 ];
then
   echo "<p> <font color="red"> <b> This is a notification email generated by automatic checks done on infor websites every 15 minutes </b> </font></p>" >> $CONTENT
   echo "<p> <font color="black"> <i> To pause this check copy stop-infor-check-${env}.txt file to host `hostname` in the /tmp folder</i> </font></p>" >> $CONTENT
   echo "</html></body>" >> $CONTENT
fi

if [ $len -eq 0 ];
then
   # first occurance of successful check remove the notification counter
   if [ -f $LOCK_FILE ];
   then
      rm -rf $LOCK_FILE 
   fi

   if [ "$1" == "-t" ];
   then
         SUBJECT="Workbrain is accessible in ${env} "
         echo "<html><body>" >> $CONTENT
         echo "<p> <font color="green"> INFOR app is up in ${env} </font></p>" >> $CONTENT
         echo "</html></body>" >> $CONTENT
   fi
fi


if [ $counter -gt $NOTIFICATION_COUNT ]; then
   exit
fi

if [ -f $CONTENT ];
then
#export CONTENT="./res.html"
(
 echo "Subject: $SUBJECT"
 echo "From: Safir Salihu<safir.salihu@wnco.com>"
 echo "MIME-Version: 1.0"
 echo "Content-Type: text/html"
 echo "Content-Disposition: inline"
 cat $CONTENT
) | /usr/sbin/sendmail $MAILTO
fi

exit 0
